MACHINE LEARNING
- a subset of AI(Artificial Intelligence)
- includes abstruse statistical tech-qs that enable machines to improve at tasks with experience.
- includes deep learning

--system learn how to combine input to predict useful prediction or never-seen data

exp:
- spam analyser of email
- picture analyser
- weather model
- system to predict stock market prices

----------------------------------------------------

VOCABULARY:
- LABEL - the thing we are predicting
- FEATURE - the input variable(s). it can be one or several features in your model

exp:
    house age(feature)   |  rooms(feature)  |  bedrooms(feature)   |  total price of house(label)
            15           |        4         |          3           |              200.000



- MODEL - the model

- Regression - a type of model which predict continuous values(temperature, price of stock market/house)

- Classification - a type of model which predict discrete values(the animal on the picture, category of mail)



Using ML to predict:
- the success of a movie in cinema
- the best next chess move
- the future success of a student



The Linear regression:
exp.
- the cricket chirps method to calculate the temperature

the math writing    y  = m.x + b;
the ML writing      y' = b + w1x1


MSE

Learning Rate - factor use to multiply the magnitude

a too small LR => too long;

a too hihg  LR => long or diverge


In [1]:
import numpy as np



In [2]:
array = np.array([1,2,3,4,5,6])
print(array)

[1 2 3 4 5 6]


In [4]:
l = [[1,2,3], [4, 3, 5 ]]
array = np.array([[1,2,3], [4, 5, 6 ]])
print(array)
print('-'*20)
print(l)

[[1 2 3]
 [4 5 6]]
--------------------
[[1, 2, 3], [4, 3, 5]]


In [5]:
array = np.array([[1,2,3], [4, 5, 6 ]])
print(array[0][1])

2


In [6]:
l0 = [1,2,3]
l1 = l0
l1[0] = 55 # will change in both lists
print(l0)
print(l1)

[55, 2, 3]
[55, 2, 3]


In [8]:
array = np.array([1,2,3])
ar1 = array.view()

ar2 = array
ar2[2]= 4
print(array)
print(ar1)
print(ar2)

[1 2 4]
[1 2 4]
[1 2 4]


In [12]:
array = np.array([1,2,3,4,5,6])
print(array.reshape((3, 2))) # 3 rows 2 column

print(array.reshape((-1, 1))) 



[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [13]:
array = np.array([1,5,9,31,45,78])
print(array.reshape(-1, 2))

[[ 1  5]
 [ 9 31]
 [45 78]]
