In [27]:
import sklearn.preprocessing as skprepro
import numpy as np
import pandas as pd
import sklearn.linear_model as skmod
import sklearn.model_selection as sksel

In [19]:
data_str = pd.read_parquet("data_streamers.parquet")

Time_of_the_day = np.array([10, 11, 1, 14, 2, 14, 9, 5, 5, 9, 0, 6, 6, 23, 19, 19, 19, 2, 4, 19, 2, 18, 4, 15, 12, 22, 12, 4, 7]).reshape(-1,1)

Number_of_viewers = np.array([23811, 47309, 25461, 9719, 30176, 5560, 45401, 43503, 40367, 20385, 26368, 2429, 29969, 37973, 17662, 37070, 5146, 47057, 1423, 46764, 25286, 46267, 4617, 9894, 14649, 2477, 16949, 47644, 4693]).reshape(-1,1)

Average_age_of_viewers = np.array([20, 16, 30, 29, 14, 21, 7, 27, 22, 15, 28, 27, 27, 17, 12, 28, 26, 11, 19, 7, 25, 17, 26, 24, 23, 27, 30, 15, 13]).reshape(-1,1)




Video_game= ["League of Legend", "Fifa", "Minecraft", "Minecraft", "Fifa", "League of Legend", "GTA V", "League of Legend", "League of Legend", "League of Legend", "Minecraft", "Minecraft", "Minecraft", "Fifa", "Fifa", "League of Legend", "Minecraft", "Fifa", "Minecraft", "GTA V", "Minecraft", "Fifa", "Minecraft", "League of Legend", "League of Legend", "Minecraft", "Minecraft", "Fifa", "League of Legend"]

In [60]:
encoder = skprepro.LabelEncoder()
encoder_games = encoder.fit_transform(Video_game)

print(encoder_games)
print(encoder.classes_)


[2 0 3 3 0 2 1 2 2 2 3 3 3 0 0 2 3 0 3 1 3 0 3 2 2 3 3 0 2]
['Fifa' 'GTA V' 'League of Legend' 'Minecraft']


In [61]:
features = np.hstack([Time_of_the_day, Number_of_viewers, Average_age_of_viewers])

model = skmod.LogisticRegression(multi_class = 'ovr').fit(features, encoder_games)


print(model.score(features, encoder_games))


0.8620689655172413


In [42]:
print(model.predict_proba(np.array([[11, 10000, 18]])))
print(model.predict_proba(np.array([[23, 1000, 30]])))

print(encoder.inverse_transform(model.predict(np.array([[11, 10000, 18]]))))
print(encoder.inverse_transform(model.predict(np.array([[23, 1000,  30]]))))


[[1.26333295e-01 1.12704196e-05 4.64051373e-01 4.09604061e-01]]
[[1.09953053e-02 1.10048111e-09 3.36041953e-01 6.52962741e-01]]
['League of Legend']
['Minecraft']


In [58]:
encoder_games = encoder_games.reshape(-1,1)
features_train, features_test, game_train, game_test = sksel.train_test_split(features, encoder_games, train_size=0.8)

print(features_train, features_test, game_train, game_test , sep='\n')

[[    6  2429    27]
 [    4 47644    15]
 [   15  9894    24]
 [   19 17662    12]
 [    5 43503    27]
 [   11 47309    16]
 [   22  2477    27]
 [   19 37070    28]
 [    0 26368    28]
 [    2 47057    11]
 [    2 30176    14]
 [   12 16949    30]
 [    2 25286    25]
 [   12 14649    23]
 [   19  5146    26]
 [    1 25461    30]
 [   18 46267    17]
 [    5 40367    22]
 [    7  4693    13]
 [   23 37973    17]
 [   19 46764     7]
 [    4  4617    26]
 [    4  1423    19]]
[[   14  5560    21]
 [    9 45401     7]
 [   10 23811    20]
 [   14  9719    29]
 [    9 20385    15]
 [    6 29969    27]]
[[3]
 [0]
 [2]
 [0]
 [2]
 [0]
 [3]
 [2]
 [3]
 [0]
 [0]
 [3]
 [3]
 [2]
 [3]
 [3]
 [0]
 [2]
 [2]
 [0]
 [1]
 [3]
 [3]]
[[2]
 [1]
 [2]
 [3]
 [2]
 [3]]


In [54]:
scaler = skprepro.StandardScaler()

x_train_std = scaler.fit_transform(features_train)
y_train_std = scaler.fit_transform(game_train)
print(x_train_std)
print(y_train_std)

[[ 0.05618858 -0.19820462 -0.06817978]
 [ 0.19978161  1.28813478 -0.63841068]
 [-1.2361487  -0.09383574  1.35739746]
 [ 0.6305607  -1.08957813  1.21483973]
 [-1.09255567  0.20440625 -0.92352612]
 [ 0.6305607  -1.35265097  0.07437794]
 [-0.08740445  1.1674464  -1.92143019]
 [-0.66177658  1.04739055  0.92972428]
 [-0.66177658  0.84902642  0.21693567]
 [-0.08740445 -0.41491237 -0.7809684 ]
 [-1.37974173 -0.03646448  1.07228201]
 [-0.51818355 -1.55069883  0.92972428]
 [-0.51818355  0.1913127   0.92972428]
 [ 1.92289798  0.69759666 -0.49585295]
 [ 1.34852586 -0.58715266 -1.20864157]
 [ 1.34852586  0.64047842  1.07228201]
 [ 1.34852586 -1.37883807  0.78716656]
 [-1.09255567  1.2721948  -1.35119929]
 [-0.80536961 -1.61433223 -0.2107375 ]
 [ 1.34852586  1.25366142 -1.92143019]
 [-1.09255567 -0.10490517  0.64460884]
 [ 1.20493282  1.22222425 -0.49585295]
 [-0.80536961 -1.41229937  0.78716656]]
[[ 0.17902872]
 [-1.46803549]
 [ 1.00256082]
 [ 1.00256082]
 [-1.46803549]
 [ 0.17902872]
 [-0.6445033